---
- name: configure apache using child playbooks
  hosts: all
  tasks:
    - name: call install playbook
      include: "{{item}}"
      with_items:
        - install.yml
        - edit_index.yml
        - restart.yml
        - check_url_response.yml
