---
- name: Install git basd on OS version
  hosts: all
  tasks:
    - name: install git using apt modules on ubuntu
      apt:
        name: git
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    - name: Install git using yum modules on RedHat
      yum:
        name: git
        state: present
        update_cache: yes
      when: ansible_distribution == "RedHat"


